// Return text generated by OpenAI API

import { NextApiRequest, NextApiResponse } from "next";
import { logger } from "../logger";
import multer from 'multer';
import { PdfData, VerbosityLevel } from 'pdfdataextract';


// disable next.js' default body parser
export const config = {
  api: { bodyParser: false }
}

// parse the pdf file into a buffer
const storage = multer.memoryStorage();
const upload = multer({ storage: storage });

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  logger.info("url:::::" + req.url);
  if (req.method === 'POST') {
    // Process a POST request
    // @ts-ignore
    upload.single('pdfFile')(req, res, function (err) {
      if (err) {
        res.status(400).json({ message: err.message })
      } else {
        // @ts-ignore
        const buffer = req.file.buffer;
        extractPdfData(buffer).then((data) => {
          res.status(200).json(data);
        });
      }
    })
  } else {
    res.status(405).json({ message: 'We only support POST' })
  }
}

export const extractPdfData = async (buffer: any) => {
  return PdfData.extract(buffer, {
    pages: 40, // how many pages should be read at most
    sort: true, // sort the text by text coordinates
    verbosity: VerbosityLevel.ERRORS, // set the verbosity level for parsing
    get: { // enable or disable data extraction (all are optional and enabled by default)
      pages: true, // get number of pages
      text: true, // get text of each page
      fingerprint: true, // get fingerprint
      outline: true, // get outline
      metadata: true, // get metadata
      info: true, // get info
      permissions: true, // get permissions
    },
  });
}
