// Return text generated by OpenAI API

import { ImageModel } from "@/models/imageModel";
import { NextApiRequest, NextApiResponse } from "next";
import { gptApi } from "../gptAPI";
import { logger } from "../logger";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  logger.info("url:::::::" + req.url);
  const imageRef = req.query.imgRef;
  // fetch all the articles.tsx from the database with the userId
  const imageData: {images: {image: string, name: string | string[] | undefined, prompt: string}[]} = {
    images: [],
  }
  
  ImageModel.find(imageRef ? { name: imageRef } : null).then((images: any) => {
    for (let i = 0; i < images.length; i++) {
      const item = images[i];
      const imageType = item.contentType;
      imageData.images.push({
        image: `data:${imageType};base64,${item.data}`,
        name: imageRef,
        prompt: item.prompt,
      });
    }
    res.status(200).json(imageData);
  });
}