// Return text generated by OpenAI API
import { NextApiRequest, NextApiResponse } from "next";
import { gptApi } from "../gptAPI";
import { logger } from "../logger";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  logger.info("url:::::" + req.url);
  const prompt = req.body.prompt;
  const response = await gptApi.getChatOneMessage(prompt);
  res.json({prompt: prompt, response: response});
}